        CREATE TABLE BLAGOVNA_SKUPINA
        (
        BLAGOVNA_SKUPINA_ID NUMBER (4) NOT NULL ,
        KNAZIV VARCHAR2 (30) ,
        DNAZIV VARCHAR2 (100)
        ) ;
        
        ALTER TABLE BLAGOVNA_SKUPINA ADD CONSTRAINT BLAGOVNA_SKUPINA_PK
        PRIMARY KEY ( BLAGOVNA_SKUPINA_ID ) ;
        CREATE TABLE DELAVEC
        (
        DELAVEC_ID NUMBER (6) NOT NULL ,
        IME VARCHAR2 (30) ,
        PRIIMEK VARCHAR2 (30) ,
        TELEFONSKA_STEVILKA VARCHAR2 (15) ,
        EMAIL VARCHAR2 (30) ,
        VODJA NUMBER (6) ,
        POPUST_NAJVEC_PROC NUMBER (6,3)
        ) ;
        
        ALTER TABLE DELAVEC ADD CONSTRAINT DELAVEC_PK PRIMARY KEY
        ( DELAVEC_ID ) ;
        CREATE TABLE DETAJL_DOKUMENTA
        (
        DETAJL_DOKUMENTA_ID NUMBER (12) NOT NULL ,
        IZDELEK_ID NUMBER (15) NOT NULL ,
        DOKUMENT_ID NUMBER (12) NOT NULL ,
        KOLICINA NUMBER (12,2) NOT NULL ,
        ENOTA_MERE VARCHAR2 (15) NOT NULL ,
        CENA_ENOTA_MERE NUMBER (14,4) ,
        POPUST_V_PROCENTIH NUMBER (6,3) NOT NULL ,
        NETO_SKUPNA_VREDNOST NUMBER (14,4) ,
        BRUTO_SKUPNA_VREDNOST NUMBER (14,4) ,
        DDV_SKUPAJ NUMBER (14,4)
        ) ;
        
        ALTER TABLE DETAJL_DOKUMENTA ADD CONSTRAINT DETAJL_DOKUMENT_PK
        PRIMARY KEY ( DETAJL_DOKUMENTA_ID ) ;
        CREATE TABLE DOKUMENT
        (
        DOKUMENT_ID NUMBER (12) NOT NULL ,
        KREIRAL_ID NUMBER (6) NOT NULL ,
        TIP_DOKUMENTA_ID NUMBER (3) NOT NULL ,
        POSLOVNI_PARTNER_ID NUMBER (6) NOT NULL ,
        REFERENCNI_DOKUMENT_ID NUMBER (12) ,
        REF_DOK_STRING VARCHAR2 (100) ,
        DATUM_KREIRANJA DATE NOT NULL ,
        DATUM_ZAPADLOSTI DATE NOT NULL ,
        DATUM_POSILJANJA DATE NOT NULL ,
        NETO_TEZA_KG NUMBER (10,2) ,
        BTO_TEZA_KG NUMBER (10,2) ,
        VALUTA_ID NUMBER (3) NOT NULL ,
        NETO_SKUPNA_VREDNOST NUMBER (10,2) ,
        BRUTO_SKUPNA_VREDNOST NUMBER (10,2) ,
        DDV_SKUPAJ NUMBER (10,2) ,
        IZVAJALEC_ID NUMBER (6)
        ) ;
        
        ALTER TABLE DOKUMENT ADD CONSTRAINT DOKUMENT_PK PRIMARY KEY
        ( DOKUMENT_ID ) ;
        CREATE TABLE ELEKTRONSKI_DOKUMENT
        (
        EDOKUMENT_ID NUMBER (12) NOT NULL ,
        LASTNIK_ID NUMBER (6) NOT NULL ,
        DATUM_SPREMEMBE DATE ,
        VSEBINA BLOB ,
        MIME_TYPE VARCHAR2 (100 BYTE) ,
        IME_IN_EKSTENZIJA VARCHAR2 (100 BYTE) ,
        KODNA_TABELA VARCHAR2 (40 BYTE)
        );
        
        ALTER TABLE ELEKTRONSKI_DOKUMENT ADD CONSTRAINT
        ELEKTRONSKI_DOKUMENT_PK PRIMARY KEY (EDOKUMENT_ID);
        CREATE TABLE DRZAVA
        (
        DRZAVA_ID VARCHAR2 (3) NOT NULL ,
        NAZIV_DRZAVE VARCHAR2 (50) ,
        REGIJA_ID NUMBER (3) NOT NULL ,
        VALUTA_ID NUMBER (3)
        ) ;
        
        ALTER TABLE DRZAVA ADD CONSTRAINT DRZAVA_PK PRIMARY KEY ( DRZAVA_ID
        ) ;
        
        CREATE TABLE ENOTA_MERE
        (
        ENOTA_MERE_ID VARCHAR2 (15) NOT NULL ,
        NAZIV VARCHAR2 (100)
        ) ;
        
        ALTER TABLE ENOTA_MERE ADD CONSTRAINT ENOTA_MERE_PK PRIMARY KEY
        ( ENOTA_MERE_ID ) ;
        
        CREATE TABLE IPS
        (
        IPS VARCHAR2 (15) NOT NULL ,
        NAZIV VARCHAR2 (50) ,
        PL_CENA NUMBER (38,2) ,
        ENM VARCHAR2 (5) ,
        ZALOGA NUMBER (38,2) ,
        OZN VARCHAR2 (3) ,
        LPE VARCHAR2 (5) ,
        ND VARCHAR2 (2) ,
        DATUM_ZALOG DATE ,
        VGRAD NUMBER (5)
        ) ;
        
        ALTER TABLE IPS ADD CONSTRAINT IPS_PK PRIMARY KEY ( IPS ) ;
        CREATE TABLE IZDELEK
        (
        IZDELEK_ID NUMBER (15) NOT NULL ,
        BLAGOVNA_SKUPINA_ID NUMBER (4) NOT NULL ,
        KNAZIV VARCHAR2 (30) ,
        DNAZIV VARCHAR2 (100) ,
        VALUTA_ID NUMBER (3) ,
        ENOTA_MERE_ID VARCHAR2 (15) NOT NULL ,
        CENA_ENOTA_MERE NUMBER (14,4) ,
        STOPNJA_DDV NUMBER (6,3) NOT NULL ,
        IPS_IPS VARCHAR2 (15) NOT NULL
        ) ;
        
        ALTER TABLE IZDELEK ADD CONSTRAINT IZDELEK_PK PRIMARY KEY
        ( IZDELEK_ID ) ;
        CREATE TABLE LPE
        (
        LPE VARCHAR2 (2) NOT NULL ,
        NAZIV VARCHAR2 (50) ,
        PROGRAM VARCHAR2 (2) ,
        KAP_KS_TED NUMBER (38,2) ,
        KAP_KS_URO NUMBER (38,5) ,
        KAP_KS_DAN NUMBER (38,5)
        ) ;
        
        ALTER TABLE LPE ADD CONSTRAINT LPE_PK PRIMARY KEY ( LPE ) ;
        CREATE TABLE LPEIPS
        (
        ZAP_ST NUMBER (11) NOT NULL ,
        LPE VARCHAR2 (2) NOT NULL ,
        IPS VARCHAR2 (15) ,
        CS_IZD_MIN NUMBER (38,2)
        ) ;
        
        ALTER TABLE LPEIPS ADD CONSTRAINT LPEIPS_PK PRIMARY KEY ( ZAP_ST ) ;
        CREATE TABLE POSLOVNI_PARTNER
        (
        POSLOVNI_PARTNER_ID NUMBER (6) NOT NULL ,
        REGIJA_ID NUMBER (3) NOT NULL ,
        NAZIV_PARTNERJA VARCHAR2 (50) ,
        POSTA_PARTNERJA VARCHAR2 (15) NOT NULL ,
        NASLOV_ULICA_DOSTAVA VARCHAR2 (50) ,
        NASLOV_POSTA_DOSTAVA VARCHAR2 (15) ,
        KONTAKT_OSEBA1_IME VARCHAR2 (30) ,
        KONTAKT_OSEBA1_TEL VARCHAR2 (15) ,
        KONTAKT_OSEBA2_IME VARCHAR2 (30) ,
        KONTAKT_OSEBA2_TEL VARCHAR2 (15) ,
        KONTAKT_WWW VARCHAR2 (50) ,
        KONTAKT_FAX VARCHAR2 (15) ,
        IBAN1 VARCHAR2 (23) ,
        BIC1 VARCHAR2 (12) ,
        IBAN2 VARCHAR2 (23) ,
        BIC2 VARCHAR2 (12) ,
        IBAN3 VARCHAR2 (23) ,
        BIC3 VARCHAR2 (12) ,
        ID_DDV VARCHAR2 (10) ,
        REG_STEVILKA_PODJETJA VARCHAR2 (30) ,
        BONITETA VARCHAR2 (5) ,
        SKRBNIK_PARTNERJA NUMBER (6) ,
        KUP_DOB VARCHAR2 (1)
        ) ;
        
        ALTER TABLE POSLOVNI_PARTNER ADD CONSTRAINT POSLOVNI_PARTNER_CON
        CHECK (KUP_DOB IN ('K', 'D', 'O','P' )) ;
        ALTER TABLE POSLOVNI_PARTNER ADD CONSTRAINT POSLOVNI_PARTNER_PK
        PRIMARY KEY ( POSLOVNI_PARTNER_ID ) ;
        CREATE TABLE POSTA
        (
        POSTNA_STEVILKA VARCHAR2 (15) NOT NULL ,
        NAZIV_POSTE VARCHAR2 (50) ,
        DRZAVA_ID VARCHAR2 (3)
        ) ;
        
        ALTER TABLE POSTA ADD CONSTRAINT POSTA_PK PRIMARY KEY
        ( POSTNA_STEVILKA ) ;
        CREATE TABLE REGIJA
        ( REGIJA_ID NUMBER (3) NOT NULL , NAZIV VARCHAR2 (100)
        ) ;
        
        ALTER TABLE REGIJA ADD CONSTRAINT REGIJA_PK PRIMARY KEY ( REGIJA_ID ) ;
        CREATE TABLE SKLADISCE
        (
        SKLADISCE_ID NUMBER (5) NOT NULL ,
        NASLOV_ULICA VARCHAR2 (30) ,
        NASLOV_POSTA VARCHAR2 (15) ,
        TELEFONSKA_STEVILKA VARCHAR2 (15) ,
        VOLUMEN_M3 NUMBER (8,2) NOT NULL ,
        POVRSINA_M2 NUMBER (8,2) NOT NULL
        ) ;
        
        ALTER TABLE SKLADISCE ADD CONSTRAINT SKLADISCE_PK PRIMARY KEY
        ( SKLADISCE_ID ) ;
        CREATE TABLE SKLADISCE_IZDELEK
        (
        SKLADISCE_ID NUMBER (5) NOT NULL ,
        IZDELEK_ID NUMBER (15) NOT NULL ,
        ZALOGA NUMBER (12,2) NOT NULL
        ) ;
        
        ALTER TABLE SKLADISCE_IZDELEK ADD CONSTRAINT SKLADISCE_IZDELEK_PK
        PRIMARY KEY ( SKLADISCE_ID, IZDELEK_ID ) ;
        CREATE TABLE STRUKTURA
        (
        ZAP_ST NUMBER (11) NOT NULL ,
        IPS VARCHAR2 (15) ,
        PODR VARCHAR2 (15) ,
        KOLICINA NUMBER (38,2)
        ) ;
        
        ALTER TABLE STRUKTURA ADD CONSTRAINT STRUKTURA_PK PRIMARY KEY
        ( ZAP_ST ) ;
        CREATE TABLE TIP_DOKUMENTA
        (
        TIP_DOKUMENTA_ID NUMBER (3) NOT NULL ,
        NAZIV VARCHAR2 (100)
        ) ;
        
        ALTER TABLE TIP_DOKUMENTA ADD CONSTRAINT TIP_DOKUMENTA_PK PRIMARY
        KEY ( TIP_DOKUMENTA_ID ) ;
        CREATE TABLE VALUTA
        (
        VALUTA_ID NUMBER (3) NOT NULL ,
        NKODA_ID NUMBER ,
        AKODA_ID VARCHAR2 (3) ,
        NAZIV_VALUTE VARCHAR2 (50) ,
        DROBIZ VARCHAR2 (10)
        ) ;
        
        CREATE TABLE POSLOVALNICA
        (
        POSLOVALNICA_ID NUMBER (6),
        NASLOV_ULICA VARCHAR2 (30),
        NASLOV_POSTA VARCHAR2 (15),
        TELEFONSKA_STEVILKA VARCHAR2 (15),
        ODP_CAS_DELAVNIK_ZAC VARCHAR2 (5),
        ODP_CAS_DELAVNIK_KONC VARCHAR2 (5),
        SKLADISCE_ID NUMBER (5)
        );
        
        CREATE TABLE EVIDENCA_DELA
        (
        EVIDENCA_DELA_ID NUMBER (12),
        DELAVEC_ID NUMBER (6),
        POSLOVALNICA_ID NUMBER (6),
        ZACETEK DATE,
        KONEC DATE
        );
        
        CREATE TABLE CENIK
        (
        CENIK_ID NUMBER (12),
        Datum_ZACETKA DATE,
        Datum_KONCA DATE,
        DELAVEC_ID NUMBER (6) NOT NULL
        );
        
        CREATE TABLE CENIK_IZDELEK
        (
        CENIK_ID NUMBER (12),
        IZDELEK_ID NUMBER (15) NOT NULL ,
        CENA_ENOTA_MERE NUMBER (14,4)
        );
        
        ALTER TABLE CENIK ADD CONSTRAINT CENIK_PK PRIMARY KEY ( CENIK_ID ) ;
        ALTER TABLE CENIK_IZDELEK ADD CONSTRAINT CENIKIYDELEK_PK PRIMARY
        KEY ( CENIK_ID, IZDELEK_ID) ;
        ALTER TABLE CENIK_IZDELEK ADD CONSTRAINT CI_FK1 FOREIGN KEY
        ( CENIK_ID ) REFERENCES CENIK (CENIK_ID) ;
        ALTER TABLE CENIK_IZDELEK ADD CONSTRAINT CI_FK2 FOREIGN KEY
        ( IZDELEK_ID ) REFERENCES IZDELEK (IZDELEK_ID) ;
        ALTER TABLE POSLOVALNICA ADD CONSTRAINT POSLOVALNICA_PK PRIMARY
        KEY ( POSLOVALNICA_ID ) ;
        ALTER TABLE EVIDENCA_DELA ADD CONSTRAINT EVIDENCA_DELA_PK PRIMARY
        KEY ( EVIDENCA_DELA_ID ) ;
        ALTER TABLE EVIDENCA_DELA ADD CONSTRAINT FK1 FOREIGN KEY
        ( DELAVEC_ID ) REFERENCES DELAVEC (DELAVEC_ID) ;
        ALTER TABLE EVIDENCA_DELA ADD CONSTRAINT FK2 FOREIGN KEY
        ( POSLOVALNICA_ID ) REFERENCES POSLOVALNICA (POSLOVALNICA_ID) ;
        ALTER TABLE POSLOVALNICA ADD CONSTRAINT FK_SKLADISCE FOREIGN KEY
        ( SKLADISCE_ID ) REFERENCES SKLADISCE ( SKLADISCE_ID ) ;
        ALTER TABLE VALUTA ADD CONSTRAINT VALUTA_PK PRIMARY KEY ( VALUTA_ID );
        ALTER TABLE DELAVEC ADD CONSTRAINT FK_DELAVEC FOREIGN KEY ( VODJA )
        REFERENCES DELAVEC ( DELAVEC_ID ) ;
        ALTER TABLE DETAJL_DOKUMENTA ADD CONSTRAINT FK_DOKUMENT_DETAJLI
        FOREIGN KEY ( DOKUMENT_ID ) REFERENCES DOKUMENT ( DOKUMENT_ID ) ;
        ALTER TABLE DOKUMENT ADD CONSTRAINT FK_DOKUMENT_VALUTA FOREIGN
        KEY ( VALUTA_ID ) REFERENCES VALUTA ( VALUTA_ID ) ;
        ALTER TABLE DRZAVA ADD CONSTRAINT FK_DRZAVA_VALUTA_ID FOREIGN KEY (
        VALUTA_ID ) REFERENCES VALUTA ( VALUTA_ID ) ;
        ALTER TABLE IZDELEK ADD CONSTRAINT FK_ENOTA_MERE_IZDELEK FOREIGN
        KEY ( ENOTA_MERE_ID ) REFERENCES ENOTA_MERE ( ENOTA_MERE_ID ) ;
        ALTER TABLE IZDELEK ADD CONSTRAINT FK_VALUTA FOREIGN KEY
        ( VALUTA_ID ) REFERENCES VALUTA ( VALUTA_ID ) ;
        ALTER TABLE LPEIPS ADD CONSTRAINT FK_IPSLPE FOREIGN KEY ( IPS )
        REFERENCES IPS ( IPS ) ON DELETE CASCADE ;
        ALTER TABLE IZDELEK ADD CONSTRAINT FK_IZDELEK_BLAGOVNA FOREIGN KEY
        ( BLAGOVNA_SKUPINA_ID ) REFERENCES BLAGOVNA_SKUPINA
        ( BLAGOVNA_SKUPINA_ID ) ;
        ALTER TABLE DETAJL_DOKUMENTA ADD CONSTRAINT
        FK_IZDELEK_DETAJLI_DOK FOREIGN KEY ( IZDELEK_ID ) REFERENCES IZDELEK
        ( IZDELEK_ID ) ;
        ALTER TABLE IZDELEK ADD CONSTRAINT FK_IZDELEK_IPS FOREIGN KEY
        ( IPS_IPS ) REFERENCES IPS ( IPS ) ;
        ALTER TABLE SKLADISCE_IZDELEK ADD CONSTRAINT FK_IZDELEK_ZALOGA
        FOREIGN KEY ( IZDELEK_ID ) REFERENCES IZDELEK ( IZDELEK_ID ) ;
        ALTER TABLE DOKUMENT ADD CONSTRAINT FK_IZVEDEL_DELAVEC FOREIGN
        KEY ( IZVAJALEC_ID ) REFERENCES DELAVEC ( DELAVEC_ID ) ;
        ALTER TABLE DOKUMENT ADD CONSTRAINT FK_KREIRAL_ID FOREIGN KEY
        ( KREIRAL_ID ) REFERENCES DELAVEC ( DELAVEC_ID ) ;
        ALTER TABLE LPEIPS ADD CONSTRAINT FK_LPEIPS FOREIGN KEY ( LPE )
        REFERENCES LPE ( LPE ) ;
        ALTER TABLE DOKUMENT ADD CONSTRAINT FK_PARTNER_DOKUMENT FOREIGN
        KEY ( POSLOVNI_PARTNER_ID ) REFERENCES POSLOVNI_PARTNER
        ( POSLOVNI_PARTNER_ID ) ;
        ALTER TABLE POSTA ADD CONSTRAINT FK_POSTA_DRZAVA_ID FOREIGN KEY
        ( DRZAVA_ID ) REFERENCES DRZAVA ( DRZAVA_ID ) ;
        ALTER TABLE POSLOVNI_PARTNER ADD CONSTRAINT FK_POSTA_PP FOREIGN
        KEY ( POSTA_PARTNERJA ) REFERENCES POSTA ( POSTNA_STEVILKA ) ;
        ALTER TABLE DOKUMENT ADD CONSTRAINT FK_REF_DOK FOREIGN KEY
        ( REFERENCNI_DOKUMENT_ID ) REFERENCES DOKUMENT ( DOKUMENT_ID ) ;
        ALTER TABLE ELEKTRONSKI_DOKUMENT ADD CONSTRAINT EDOKUMENT_FK
        FOREIGN KEY (EDOKUMENT_ID) REFERENCES DOKUMENT ( DOKUMENT_ID ) ;
        ALTER TABLE DRZAVA ADD CONSTRAINT FK_REGIJA_ID_DRZAVA FOREIGN KEY
        ( REGIJA_ID ) REFERENCES REGIJA ( REGIJA_ID ) ;
        ALTER TABLE POSLOVNI_PARTNER ADD CONSTRAINT
        FK_REGIJA_POSLOVNI_PARTNER FOREIGN KEY ( REGIJA_ID ) REFERENCES
        REGIJA ( REGIJA_ID ) ;
        ALTER TABLE SKLADISCE_IZDELEK ADD CONSTRAINT FK_SKLADISCE_ZALOGA
        FOREIGN KEY ( SKLADISCE_ID ) REFERENCES SKLADISCE ( SKLADISCE_ID ) ;
        ALTER TABLE POSLOVNI_PARTNER ADD CONSTRAINT FK_SKRBNIK_ID FOREIGN
        KEY ( SKRBNIK_PARTNERJA ) REFERENCES DELAVEC ( DELAVEC_ID ) ;
        ALTER TABLE STRUKTURA ADD CONSTRAINT FK_SESTAV FOREIGN KEY ( IPS )
        REFERENCES IPS ( IPS ) ON
        DELETE CASCADE ;
        ALTER TABLE STRUKTURA ADD CONSTRAINT FK_SESTAVNI_DEL FOREIGN KEY
        ( PODR ) REFERENCES IPS ( IPS ) ON
        DELETE CASCADE ;
        ALTER TABLE DOKUMENT ADD CONSTRAINT FK_TIP_DOK FOREIGN KEY
        ( TIP_DOKUMENTA_ID ) REFERENCES TIP_DOKUMENTA ( TIP_DOKUMENTA_ID ) ;
